# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  update-api:
    cmds:
      - GOPROXY=direct go get -u github.com/puupee/puupee-api-go
