# https://taskfile.dev

version: "3"

vars:
  GIT_COMMIT:
    sh: git rev-parse --short HEAD
  GIT_LAST_TAG:
    sh: git describe --abbrev=0 --tags

tasks:
  update-api:
    cmds:
      - GOPROXY=direct go get -u github.com/puupee/puupee-api-go
  install:
    cmds:
      - go install -ldflags="-X 'github.com/puupee/puupee-sdk-go/buildinfo.Version={{.GIT_LAST_TAG}}-{{.GIT_COMMIT}}' -X 'github.com/puupee/puupee-sdk-go/buildinfo.Host={{.HOST}}' -X 'github.com/puupee/puupee-sdk-go/buildinfo.BuildTime=$(date)'" ./cmd/puupee
    vars:
      HOST: "api.puupee.com"
